name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Linter
        run: ruff check .

      - name: Run tests
        run: python -m pytest --junitxml=report.xml # <-- Changed: generates report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4 # <-- New: The save action
        if: always() # <-- New: Crucial! Save the report even if tests fail
        with:
          name: test-results-report # The name of the artifact
          path: report.xml # The file to save

      - name: Run secret script
        run: python print_secret.py
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }} # <-- New
