name: My First Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello, CI/CD World!"
      - name: SHow current date and time
        run: date
